hosts: localhost
name: creating ec2 instance
tasks: 
- amazon.aws.ec2_instance:
        name: "public-compute-instance"
        key_name: "ansible"
        vpc_subnet_id: subnet-0442b2512ebfa8c27
        instance_type: t2.micro
        security_group: default
        network:
          assign_public_ip: true
        image_id: ami-0f5ee92e2d63afc18
        tags:
          Environment: Testing
